v12mike_enhancednotificationemails_route:
        path: /unsubscribe/{target_user_id}/{notification_type}/{identifier}/{time_stamp}/{token}
        defaults: { _controller:v12mike.enhancednotificationemails.controller:handle}
        requirements:
            target_user_id: '\d{1,7}'
            notification_type: '\d{1,2}'
            identifier: '\d{1,8}'
            time_stamp: '\d{1,6}'
            token:      '([0-9]|[a-f]|[A-F]){10}'

